### ISSUE TITLE
aws signature v4 - new headers

### ISSUE THREAD

**Issue by zarfix** [danieljoos/aws-sign-web#14]
Hi Daniel,
thank for lib, it's awesome ! :)
I try to use it in a personnal project but I have problems about authorization.
Now, aws s3 signature v4 impose new header (X-Amz-Content-Sha256) and signedheaders (x-amz-content-sha256;x-amz-date;x-amz-security-token).
So I include it in your code but it doesn't work. Amazon server reply that my signature doesn't match (isn't good).
Are you still using your library ? does it work ?
Can I send you my code (your lib with my changes) to have your opinion ?
Thank you :)

**Comment by zarfix** [comment]
Hi Daniel,
I resolved my problem.
Thank you again for your script, nice work :)

**Comment by danieljoos** [comment]
Hi @zarfix ,
Sorry for the late reply. I don't actively use the library at the moment.
Troubleshooting wrong signatures is a mess. You just know *that* something is wrong, but you don't know *where*....

Cheers,
Daniel
