### ISSUE TITLE
Using the `params` field of `AxiosRequestConfig` crashes the new multi-value query param code

### ISSUE THREAD

**Issue by mrmilosz** [danieljoos/aws-sign-web#20]
In

https://github.com/danieljoos/aws-sign-web/blob/4388cd692dadebfb0bbd2e2778fee550af8aed05/aws-sign-web.js#L130-L132

`ws.uri.queryParams` is parsed from the URI by

https://github.com/danieljoos/aws-sign-web/blob/4388cd692dadebfb0bbd2e2778fee550af8aed05/aws-sign-web.js#L249-L262

into an object whose values are arrays, and so if `ws.request.params` is empty, then in

https://github.com/danieljoos/aws-sign-web/blob/4388cd692dadebfb0bbd2e2778fee550af8aed05/aws-sign-web.js#L146-L149

the assumption that `ws.uri.queryParams[key]` has a `sort` method is valid.

However, `ws.request.params` has not undergone any kind of sanitation and can have non-array values, which crashes the above code.

I ran into this problem when attempting to use `config.params` during a GET request and I have no idea how no one else has run into this! Right now I'm working around this using a custom interceptor in my axios code, which moves `config.params` into the URI:

```typescript
client.interceptors.request.use((config) => {
  if (config.params !== undefined) {
    config.url = client.getUri(config);
    config.params = undefined;
  }
  return config;
});
```

However, I think that to properly address the issue we'd need to either make that signing code handle the non-array case, or sanitize `ws.request.params` before running extend, by turning its non-array values into arrays.

**Comment by danieljoos** [comment]
Hi,

Thanks a lot for bringing this up. Same for #17, I seem to have missed that one completely.
I fully agree with you that the signing code should validate the `params`.

I'd really welcome your contribution, here.

Cheers,
Daniel

**Comment by mrmilosz** [comment]
I've created a pull request. I'll reference it in the other issue as well.

**Comment by mrmilosz** [comment]
I've created another pull request to bump the version so that people can actually use this code: https://github.com/danieljoos/aws-sign-web/pull/22

Otherwise I consider this issue closed, so I'm closing it.
