### ISSUE TITLE
Passing awsAuth values using ngResource

### ISSUE THREAD

**Issue by fromhell13** [danieljoos/aws-sign-web#4]
Hi, how if i want to use your injector in $resource? i'm new to angular and help you can guide

**Comment by jamey-taylor** [comment]
The signature calculated will not match if a uri segment contains a colon. AWS will encode the colon to %3A, but aws-sign-web will not.

e.g GET https://my-apigateway-app.com/users/us-east-1:deadbeef-dead-beef-dead-beef00000075/items/

AWS will show that the string to encode changed the colon 2nd segment of the path to %3A when calculating the signature.
