### ISSUE TITLE
Signature does not match if uri segment contains a colon

### ISSUE THREAD

**Issue by jamey-taylor** [danieljoos/aws-sign-web#5]
The signature calculated will not match if a uri segment contains a colon. AWS will encode the colon to %3A, but aws-sign-web will not.

e.g GET https://my-apigateway-app.com/users/us-east-1:deadbeef-dead-beef-dead-beef00000075/items/

AWS will show that the string to encode changed the colon 2nd segment of the path to %3A when calculating the signature.

**Comment by jamey-taylor** [comment]
I fixed my local copy on line 135 with the change below and it seems to be working:

            //encodeURI(ws.uri.path) + '\n' +
            ws.uri.path.split("/").map((seg) => { return encodeURIComponent(seg); }).join("/") + '\n' +

**Comment by danieljoos** [comment]
Interesting. Wasn't aware that `encodeURI` doesn't encode all characters correctly. Thanks for your fix - looks good! Would you mind creating a PR for it? ;-)

**Comment by jamey-taylor** [comment]
Done. Thanks!

**Comment by danieljoos** [comment]
Thanks for the contribution. I'll trigger a new npm packge release later today.
